dist: trusty
language: python
python:
  - 3.6
  - 3.7

cache:
  directories:
    - $HOME/virtualenv/python3.6/
    - $HOME/virtualenv/python3.7/

jobs:
  include:
    - stage: tests
      script: tox

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: serenata
        password: $PYPI_PASSWORD
        distributions: "sdist bdist_wheel"
        on:
          branch: master

before_install:
  - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install 3.6.8
  - pyenv install 3.7.3
  - pyenv local 3.6.8 3.7.3
install:
  - coverage erase
  - python -m pip install -U tox
  - python -m pip install -U -e .

after_success:
  - coverage combine
  - coverage report
  - coveralls
